#!/bin/sh

# PROVIDE: mangadexathome

. /etc/rc.subr

name="mangadexathome"
user="mangadexathome"
rcvar=`set_rcvar`
pidfile="/var/run/mangadexathome.pid"
start_cmd="${name}_start"
stop_cmd="${name}_stop"

load_rc_config $name

mangadexathome_start()
{
    if checkyesno ${rcvar}; then
      echo "Starting mangadexathome"
      cd /usr/home/mangadexathome/mangadexathome
      /usr/sbin/daemon -p $pidfile -u $user java -Dfile-level=info -Dstdout-level=off -jar mangadex_at_home.jar > /dev/null 2>&1
    fi
}

mangadexathome_stop()
{
    if [ -e $pidfile ]; then
        read pid < $pidfile
        case $pid in
            *[!0-9]*) echo "$pidfile is not a valid pid file" ;;
            *) echo "Stopping mangadexathome (this may take a minute). pid: $pid"
               kill $pid 
               pwait $pid
               echo "mangadexathome ($pid) is now dead" ;;
        esac
    else
        echo "$pidfile does not exist (is mangadexathome running?)"
    fi
}

run_rc_command "$1"

